/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.awt.AWTException;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException, AWTException {
        TestCases tests = new TestCases(); // Initialize your test class

       //  tests.testCase01(); //TODO: call your test case functions one after other here 
       
// I created seperate classes for every task
       SearchAmazon sa = new SearchAmazon();
      // sa.searchAmazon();

        CountHyperlinks hyper = new CountHyperlinks();
       // hyper.countLinks();

       TextLinkedin lin = new TextLinkedin();
       //lin.textPost();

       GoogleNameLinks name= new GoogleNameLinks();
       //name.nameLinks();

       ImageUrl iurl = new ImageUrl();
       //iurl.imgUrl();

        NestedFrames nf = new NestedFrames();
        nf.nFrame();

        IMDBRatings imdbr = new IMDBRatings();
        //imdbr.imdb();
        
        WindowHandle wh = new WindowHandle();
        wh.winHandle();

       ImageLinkedin imglinked = new ImageLinkedin();
       //imglinked.imagePost();

       VideoLinkedin vlinked = new VideoLinkedin();
       //vlinked.videoPost();
        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, IOException, AWTException {
        new App().getGreeting();
    }
}
